/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as ApiPublicProductPreviewRouteImport } from './routes/api/public/product-preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductPreviewRoute = ApiPublicProductPreviewRouteImport.update({
  id: '/api/public/product-preview',
  path: '/api/public/product-preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection/$id': typeof CollectionIdRoute
  '/api/public/product-preview': typeof ApiPublicProductPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection/$id': typeof CollectionIdRoute
  '/api/public/product-preview': typeof ApiPublicProductPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection/$id': typeof CollectionIdRoute
  '/api/public/product-preview': typeof ApiPublicProductPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection/$id' | '/api/public/product-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection/$id' | '/api/public/product-preview'
  id: '__root__' | '/' | '/collection/$id' | '/api/public/product-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionIdRoute: typeof CollectionIdRoute
  ApiPublicProductPreviewRoute: typeof ApiPublicProductPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-preview': {
      id: '/api/public/product-preview'
      path: '/api/public/product-preview'
      fullPath: '/api/public/product-preview'
      preLoaderRoute: typeof ApiPublicProductPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionIdRoute: CollectionIdRoute,
  ApiPublicProductPreviewRoute: ApiPublicProductPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
